POST http://localhost:3003/TodoListUser
Content-Type: application/json

{
    
	"name": "Astro Dev",
	"nickname": "astrodev",
	"email": "astro@dev.com"

}
###
GET http://localhost:3003/TodoListUser/:id